# Generated by Django 2.2.7 on 2019-11-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahaDiscom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct', models.CharField(max_length=300)),
                ('cn', models.CharField(max_length=300)),
                ('bun', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
