# Generated by Django 2.2.7 on 2019-11-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191107_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahadiscom',
            name='kW',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
