# Generated by Django 2.2.7 on 2019-11-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_mahadiscom_kw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahadiscom',
            name='kW',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
