# Generated by Django 2.2.7 on 2019-11-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191108_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahadiscom',
            name='kW',
            field=models.CharField(max_length=300, null='True'),
        ),
    ]
