# Generated by Django 2.2.7 on 2019-11-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191108_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahadiscom',
            old_name='title',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='mahadiscom',
            old_name='content',
            new_name='password',
        ),
    ]
