# Generated by Django 2.2.7 on 2019-11-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191109_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='compost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='footprint',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='journey_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='meal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='solar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
