# Generated by Django 2.2.7 on 2019-11-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191109_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bun',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='cn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ct',
            field=models.IntegerField(default=0),
        ),
    ]
